# Generated by Django 5.2.5 on 2025-08-19 19:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kundennummer', models.IntegerField(verbose_name='Kundennummer')),
                ('kundenname', models.CharField(max_length=50, verbose_name='Kundenname')),
            ],
            options={
                'db_table': 'tbl_kunde',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialnummer', models.IntegerField(verbose_name='Materialnummerr')),
                ('bezeichnung', models.CharField(max_length=39, verbose_name='Bezeichnung')),
            ],
            options={
                'db_table': 'tbl_material',
            },
        ),
        migrations.CreateModel(
            name='StatusKomponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komponente_auswahl', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tbl_statuskomponente',
            },
        ),
        migrations.CreateModel(
            name='StatusKundenauftrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_auswahl', models.CharField(default='---', max_length=20)),
            ],
            options={
                'db_table': 'tbl_statuskundenauftrage',
            },
        ),
        migrations.CreateModel(
            name='StatusProdukt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produkt_auswahl', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tbl_statusprodukt',
            },
        ),
        migrations.CreateModel(
            name='Kundenauftrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kundenauftrag', models.IntegerField(verbose_name='Kundenauftrag')),
                ('kundenname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kdname', to='app_auelb.kunde')),
                ('statuskundenauftrag', models.ForeignKey(default='---', on_delete=django.db.models.deletion.CASCADE, related_name='rel_statkd', to='app_auelb.statuskundenauftrag')),
            ],
            options={
                'db_table': 'tbl_kundenauftrage',
            },
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_auftragsmenge', models.CharField(blank=True, max_length=20, null=True)),
                ('p_fertigungsauftrag', models.CharField(blank=True, max_length=10, null=True)),
                ('p_endtermin', models.DateField(default=datetime.date.today)),
                ('bezeichnung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kdbezeichnung', to='app_auelb.material')),
                ('kundenauftrag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_back_1', to='app_auelb.kundenauftrag')),
                ('statusprodukt', models.ForeignKey(default='---', on_delete=django.db.models.deletion.CASCADE, to='app_auelb.statusprodukt')),
            ],
            options={
                'db_table': 'tbl_produkt',
            },
        ),
        migrations.CreateModel(
            name='Komponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k_auftragsmenge', models.CharField(blank=True, max_length=20, null=True)),
                ('k_fertigungsauftrag', models.CharField(blank=True, max_length=10, null=True)),
                ('k_endtermin', models.DateField(default=datetime.date.today)),
                ('bezeichnung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kdbezeichnung_komp', to='app_auelb.material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_back_2', to='app_auelb.produkt')),
                ('statuskomponente', models.ForeignKey(default='---', on_delete=django.db.models.deletion.CASCADE, to='app_auelb.statuskomponente')),
            ],
            options={
                'db_table': 'tbl_komponente',
            },
        ),
    ]
