# Generated by Django 5.2.5 on 2025-09-04 05:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auelb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kundenauftrag',
            name='v_endtermin',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='kundenauftrag',
            name='statuskundenauftrag',
            field=models.ForeignKey(blank=True, default='---', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_statkd', to='app_auelb.statuskundenauftrag'),
        ),
        migrations.AlterField(
            model_name='material',
            name='materialnummer',
            field=models.IntegerField(verbose_name='Materialnummer'),
        ),
    ]
