# Generated by Django 5.2.5 on 2025-09-04 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auelb', '0002_kundenauftrag_v_endtermin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kundenauftrag',
            name='statuskundenauftrag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_statkd', to='app_auelb.statuskundenauftrag'),
        ),
        migrations.AlterField(
            model_name='statuskundenauftrag',
            name='kd_auswahl',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Merkmale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_durchmesser', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('m_gewicht', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('materialnummer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mat_merkmal', to='app_auelb.material')),
            ],
            options={
                'db_table': 'tbl_merkmale',
            },
        ),
    ]
