# Generated by Django 5.2.5 on 2025-09-04 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auelb', '0003_alter_kundenauftrag_statuskundenauftrag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komponente',
            name='statuskomponente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_auelb.statuskomponente'),
        ),
        migrations.AlterField(
            model_name='merkmale',
            name='materialnummer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merkmale', to='app_auelb.material'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='statusprodukt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_auelb.statusprodukt'),
        ),
    ]
