# Generated by Django 5.2.5 on 2025-09-10 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auelb', '0004_alter_komponente_statuskomponente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='komponente',
            options={'verbose_name': 'Komponente', 'verbose_name_plural': 'Komponenten'},
        ),
        migrations.AlterModelOptions(
            name='kunde',
            options={'verbose_name': 'Kunde', 'verbose_name_plural': 'Kunden'},
        ),
        migrations.AlterModelOptions(
            name='kundenauftrag',
            options={'verbose_name': 'Kundenauftrag', 'verbose_name_plural': 'Kundenaufträge'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Material', 'verbose_name_plural': 'Materialien'},
        ),
        migrations.AlterModelOptions(
            name='merkmale',
            options={'verbose_name': 'Merkmal', 'verbose_name_plural': 'Merkmale'},
        ),
        migrations.AlterModelOptions(
            name='produkt',
            options={'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkte'},
        ),
        migrations.AlterModelOptions(
            name='statuskomponente',
            options={'verbose_name': 'Status Komponente', 'verbose_name_plural': 'Status Komponenten '},
        ),
        migrations.AlterModelOptions(
            name='statuskundenauftrag',
            options={'verbose_name': 'Status Kundenauftrag', 'verbose_name_plural': 'Status Kundenaufträge'},
        ),
        migrations.AlterModelOptions(
            name='statusprodukt',
            options={'verbose_name': 'Status Produkt', 'verbose_name_plural': 'Status Produkte'},
        ),
        migrations.AlterField(
            model_name='produkt',
            name='kundenauftrag',
            field=models.ForeignKey(default='---', on_delete=django.db.models.deletion.CASCADE, related_name='order_back_1', to='app_auelb.kundenauftrag'),
        ),
    ]
