# Generated by Django 5.2.5 on 2025-09-10 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auelb', '0005_alter_komponente_options_alter_kunde_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kundenauftrag',
            name='kundenauftrag',
            field=models.IntegerField(default='---', verbose_name='Kundenauftrag'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='kundenauftrag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_back_1', to='app_auelb.kundenauftrag'),
        ),
    ]
