# Generated by Django 5.2.5 on 2025-09-10 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auelb', '0006_alter_kundenauftrag_kundenauftrag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komponente',
            name='statuskomponente',
            field=models.ForeignKey(default='---', on_delete=django.db.models.deletion.CASCADE, to='app_auelb.statuskomponente'),
        ),
        migrations.AlterField(
            model_name='kundenauftrag',
            name='statuskundenauftrag',
            field=models.ForeignKey(blank=True, default='---', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_statkd', to='app_auelb.statuskundenauftrag'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='statusprodukt',
            field=models.ForeignKey(default='---', on_delete=django.db.models.deletion.CASCADE, to='app_auelb.statusprodukt'),
        ),
        migrations.AlterField(
            model_name='statuskundenauftrag',
            name='kd_auswahl',
            field=models.CharField(default='---', max_length=20),
        ),
    ]
