# Generated by Django 5.2.5 on 2025-09-18 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auelb', '0007_alter_komponente_statuskomponente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urblatt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_schnittwerkzeug', models.CharField(max_length=20, verbose_name='Schnittwerkzeug')),
                ('materialnummer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urblatt', to='app_auelb.material')),
            ],
            options={
                'verbose_name': 'Urblatt',
                'verbose_name_plural': 'Urblatt',
                'db_table': 'tbl_urblatt',
            },
        ),
    ]
