# Generated by Django 5.2.5 on 2025-09-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auelb', '0008_urblatt'),
    ]

    operations = [
        migrations.AddField(
            model_name='urblatt',
            name='u_bild',
            field=models.ImageField(blank=True, null=True, upload_to='urblatt_bilder/', verbose_name='Bild'),
        ),
    ]
