# Generated by Django 5.2.5 on 2025-09-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auelb', '0009_urblatt_u_bild'),
    ]

    operations = [
        migrations.AddField(
            model_name='merkmale',
            name='m_bild',
            field=models.ImageField(blank=True, null=True, upload_to='urblatt_bilder/', verbose_name='Bild'),
        ),
    ]
