# Generated by Django 5.2.5 on 2025-10-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auelb', '0010_merkmale_m_bild'),
    ]

    operations = [
        migrations.AddField(
            model_name='kundenauftrag',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='kundenauftraege/', verbose_name='Bild'),
        ),
    ]
