# Generated by Django 5.2.5 on 2025-10-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auelb', '0011_kundenauftrag_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='komponente',
            name='k_infofeld',
            field=models.TextField(blank=True, null=True, verbose_name='Infofeld'),
        ),
        migrations.AddField(
            model_name='kundenauftrag',
            name='kun_infofeld',
            field=models.TextField(blank=True, null=True, verbose_name='Infofeld'),
        ),
        migrations.AddField(
            model_name='produkt',
            name='p_infofeld',
            field=models.TextField(blank=True, null=True, verbose_name='Infofeld'),
        ),
    ]
