# Generated by Django 5.2.5 on 2025-10-16 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auelb', '0012_komponente_k_infofeld_kundenauftrag_kun_infofeld_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='p_endtermin_wunsch',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='produkt',
            name='p_kalkpreis',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='produkt',
            name='p_servieanfrage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='merkmale',
            name='m_bild',
            field=models.ImageField(blank=True, null=True, upload_to='merkmale_bilder/', verbose_name='Bild'),
        ),
    ]
