# Generated by Django 5.2.5 on 2025-10-16 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auelb', '0013_produkt_p_endtermin_wunsch_produkt_p_kalkpreis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produkt',
            old_name='p_servieanfrage',
            new_name='p_serviceanfrage',
        ),
    ]
