# Generated by Django 5.2.5 on 2025-11-10 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auelb', '0014_rename_p_servieanfrage_produkt_p_serviceanfrage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komponente',
            name='statuskomponente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_auelb.statuskomponente'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='statusprodukt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_auelb.statusprodukt'),
        ),
        migrations.AlterField(
            model_name='statuskundenauftrag',
            name='kd_auswahl',
            field=models.CharField(max_length=20),
        ),
    ]
