# Generated by Django 5.2.5 on 2025-11-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auelb', '0015_alter_komponente_statuskomponente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kundenauftrag',
            name='kundenauftrag',
            field=models.IntegerField(verbose_name='Kundenauftrag'),
        ),
    ]
