# Generated by Django 5.2.5 on 2025-11-10 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auelb', '0016_alter_kundenauftrag_kundenauftrag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='komponente',
            name='k_infofeld',
        ),
        migrations.RemoveField(
            model_name='kundenauftrag',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='kundenauftrag',
            name='kun_infofeld',
        ),
        migrations.RemoveField(
            model_name='merkmale',
            name='m_bild',
        ),
        migrations.RemoveField(
            model_name='produkt',
            name='p_endtermin_wunsch',
        ),
        migrations.RemoveField(
            model_name='produkt',
            name='p_infofeld',
        ),
        migrations.RemoveField(
            model_name='produkt',
            name='p_kalkpreis',
        ),
        migrations.RemoveField(
            model_name='produkt',
            name='p_serviceanfrage',
        ),
        migrations.AlterField(
            model_name='komponente',
            name='statuskomponente',
            field=models.ForeignKey(default='---', on_delete=django.db.models.deletion.CASCADE, to='app_auelb.statuskomponente'),
        ),
        migrations.AlterField(
            model_name='kundenauftrag',
            name='kundenauftrag',
            field=models.IntegerField(default='---', verbose_name='Kundenauftrag'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='statusprodukt',
            field=models.ForeignKey(default='---', on_delete=django.db.models.deletion.CASCADE, to='app_auelb.statusprodukt'),
        ),
        migrations.AlterField(
            model_name='statuskundenauftrag',
            name='kd_auswahl',
            field=models.CharField(default='---', max_length=20),
        ),
    ]
