# Generated by Django 5.2.5 on 2025-11-10 16:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auelb', '0017_remove_komponente_k_infofeld_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='komponente',
            name='k_infofeld',
            field=models.TextField(blank=True, null=True, verbose_name='Infofeld'),
        ),
        migrations.AddField(
            model_name='kundenauftrag',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='kundenauftraege/', verbose_name='Bild'),
        ),
        migrations.AddField(
            model_name='kundenauftrag',
            name='kun_infofeld',
            field=models.TextField(blank=True, null=True, verbose_name='Infofeld'),
        ),
        migrations.AddField(
            model_name='merkmale',
            name='m_bild',
            field=models.ImageField(blank=True, null=True, upload_to='merkmale_bilder/', verbose_name='Bild'),
        ),
        migrations.AddField(
            model_name='produkt',
            name='p_endtermin_wunsch',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='produkt',
            name='p_infofeld',
            field=models.TextField(blank=True, null=True, verbose_name='Infofeld'),
        ),
        migrations.AddField(
            model_name='produkt',
            name='p_kalkpreis',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='produkt',
            name='p_serviceanfrage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='komponente',
            name='statuskomponente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_auelb.statuskomponente'),
        ),
        migrations.AlterField(
            model_name='kundenauftrag',
            name='kundenauftrag',
            field=models.IntegerField(verbose_name='Kundenauftrag'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='statusprodukt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_auelb.statusprodukt'),
        ),
        migrations.AlterField(
            model_name='statuskundenauftrag',
            name='kd_auswahl',
            field=models.CharField(max_length=20),
        ),
    ]
