# Generated by Django 5.2.5 on 2025-11-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auelb', '0018_komponente_k_infofeld_kundenauftrag_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='komponente',
            name='k_serviceanfrage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
