# Generated by Django 5.2.5 on 2025-11-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auelb', '0019_komponente_k_serviceanfrage'),
    ]

    operations = [
        migrations.AddField(
            model_name='komponente',
            name='k_frei',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='produkt',
            name='p_frei',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
