# Generated by Django 5.2.5 on 2025-11-12 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auelb', '0020_komponente_k_frei_produkt_p_frei'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='p_LT_EXP',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
